Update narratives based on version in at narrative_version url
kbase/narrative-traefiker pull request #1
Opened 2020-04-04 04:14 UTC by sychan

This feature branch adds functionality to the reaper process that:

1) implements a query to a narrative_version endpoint ( currently configured in narrative_version_url defaulting to "https://narrative.kbase.us/narrative_version" ).
2) If the version query completes and returns a version string, it becomes the new required version (note - this can actually be a lower version than the previous value) and any existing prespawned narratives that have a lower version number get reaped.
3) Whether or not the required version is updated, the reaper checks to see if there are the required number of prespawned narratives - if not, enough new narratives are spawned to match cfg['num_prespawn']. This is how any old narratives reaped in step 2 above get replenished. This also allows admins to manually delete prespawned containers and have them replenished automatically.

2020-04-04 21:56 UTC, kkellerlbl commented
"any existing prespawned narratives that have a lower version number get reaped."    Perhaps it is better to reap narratives with a different version, higher or lower?  This way we can roll back to a previous version of a narrative image if we need to.  Is there a downside to that?

2020-04-04 22:04 UTC, kkellerlbl requested changes
First pass.  I am still reading the new code in reaper() and in manage_rancher.

edit: reviewed other code, no new comments.

2020-04-04 22:04 UTC, kkellerlbl commented on app.py
> +       "narrative_version_url": "https://narrative.kbase.us/narrative_version",
If we're setting defaults, I think they should all be for one deploy env.  So we should either change this to match using CI in auth2, or we should change the default value auth2 to use prod.  (I think I prefer defaulting to prod, but it's not a strong preference.)

2020-04-04 22:04 UTC, kkellerlbl commented on app.py
> +    Reaps prespawned narratives that are older than the version string passed in
May be better to reap narratives with a different version instead of lower, to make rolling back easier?

2020-04-06 02:44 UTC, sychan commented on app.py
> +       "narrative_version_url": "https://narrative.kbase.us/narrative_version",
Good point, I settled on ci for now.

2020-04-06 02:44 UTC, sychan commented on app.py
> +    Reaps prespawned narratives that are older than the version string passed in
I've changed it to from less than to not-equal

2020-04-06 02:45 UTC, sychan commented
@kkellerlbl Please look over the changes. I also added comments for all of the cfg entries, since I managed to forget a few of them after writing them 3 months ago!

2020-04-06 19:44 UTC, bio-boris approved these changes
Looks good to me.

2020-04-06 22:54 UTC, sychan commented
@kkellerlbl @jsfillman Do you have an issues with me merging this this evening?

2020-04-07 15:53 UTC, kkellerlbl approved these changes
Looks good.

2020-04-07 16:06 UTC, merged